# .readthedocs.yaml

version: 2

# Configuration des dépendances Python
python:
  version: "3.11.5"  # Assure-toi d'utiliser la version correcte de Python
  install:
    - requirements: requirements.txt  # Le fichier requirements.txt contenant toutes les dépendances nécessaires
    - method: pip
      path: .  # Utilise la méthode pip pour installer les dépendances à partir du répertoire actuel

# Configuration de Sphinx pour la génération de la documentation
sphinx:
  configuration: docs/source/conf.py  # Chemin vers ton fichier de configuration Sphinx 

# Configuration des outils de construction (build tools)
build:
  image: "ubuntu-20.04"  
  tools:
    python:
      version: "3.11"  # Version de Python à utiliser pendant la construction de la doc

# Variables d'environnement 
env:
  DJANGO_SETTINGS_MODULE: "oc_lettings_site.settings"  
