# .readthedocs.yaml

version: 2

# Configuration des dépendances
python:
  version: "3.11.5"  # Mets la version de Python que tu utilises
  install:
    - requirements: requirements.txt  # Assure-toi d'avoir un requirements.txt avec toutes les dépendances
    - method: pip
      path: .

# Construction de la documentation avec Sphinx
sphinx:
  configuration: docs/source/conf.py  # Spécifie le chemin vers le fichier de configuration Sphinx (habituellement dans le dossier 'docs')

# Build tools configuration
build:
  image: "latest"  # Utilise l'image la plus récente fournie par Read the Docs pour gérer les dépendances récentes

env:
  DJANGO_SETTINGS_MODULE: "oc_lettings_site.settings"  
