services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static_volume:/app/staticfiles
    expose:
      - "8000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"  
    volumes:
      - static_volume:/usr/share/nginx/html/static  
    depends_on:
      - web

volumes:
  static_volume:
