services:
  django_gunicorn:
    build:
      context: .
      dockerfile: Dockerfile
    image: edwin350/django_gunicorn:latest
    volumes:
      - static:/app/staticfiles
    env_file:
      - .env



  nginx:
    build: ./nginx 
    image: edwin350/nginx:latest
    volumes:
      - static:/static
    ports:
      - "80:80"    
    depends_on:
      - django_gunicorn


volumes:
  static:
