# Utiliser l'image Nginx officielle comme image de base
FROM nginx:latest

# Copier le fichier de configuration Nginx personnalisé dans le conteneur
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
