name: Django CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django migrations
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: python manage.py migrate

      - name: Run linting with Flake8
        run: flake8 --max-line-length=99 .

      - name: Run tests with pytest & coverage
        run: |
          pytest --cov-config=.coveragerc
          coverage report --fail-under=80
      
      # Build Docker images
      - name: Build Docker images
        run: |
          docker buildx build -t "edwin350/django_gunicorn:latest" .
          docker buildx build -t "edwin350/nginx:latest" -f ./nginx/Dockerfile .

      # Docker Hub login
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Push to Docker Hub
      - name: Push Docker images
        run: |
          docker push edwin350/nginx:latest
          docker push edwin350/django_gunicorn:latest

