name: Django CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations
        run: python manage.py migrate

      - name: Run tests with pytest & coverage
        run: |
          pytest --cov-config=.coveragerc
      
      # Étape pour construire l'image Docker
      - name: Build Docker image
        run: |
          docker build -t edwin350/oc_lettings:latest .

      # Étape pour se connecter à Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Étape pour pousser l'image vers Docker Hub
      - name: Push Docker image
        run: docker push edwin350/oc_lettings:latest

