name: Django CI
on:
  push:
    branches:
      - master
      - tests/docker
  pull_request:
    branches:
      - master
      - tests/docker

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django migrations
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: python manage.py migrate

      - name: Run linting with Flake8
        run: flake8 --max-line-length=99 .

      - name: Run tests with pytest & coverage
        run: |
          pytest --cov-config=.coveragerc
          coverage report --fail-under=80

      # Étape pour se connecter à Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            # Étape pour construire et démarrer les services avec docker-compose
      - name: Build and run Docker containers
        run: |
          docker-compose up --build -d

      # Étape pour pousser les images construites par docker-compose
      - name: Push Docker image
        run: |
          docker-compose push

