name: Django CI
on:
  push:
    branches:
      - master
      - tests/docker
  pull_request:
    branches:
      - master
      - tests/docker

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django migrations
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: python manage.py migrate

      - name: Run linting with Flake8
        run: flake8 --max-line-length=99 .

      - name: Run tests with pytest & coverage
        run: |
          pytest --cov-config=.coveragerc
          coverage report --fail-under=80

      # Étape pour installer Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      
      # Build Docker images with commit hash
      - name: Build Docker images
        run: docker-compose build

      # Étape pour se connecter à Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Étape pour pousser l'image vers Docker Hub
      # Tag and Push the built images
      - name: Push Docker images
        run: |
          docker tag edwin350/django_gunicorn:latest edwin350/django_gunicorn:latest
          docker tag edwin350/nginx:latest edwin350/nginx:latest
          docker push edwin350/django_gunicorn:${{ github.sha }}
          docker push edwin350/nginx:${{ github.sha }}

